##################################################
############ 应用相关配置 ##########################
##################################################
application:
  backend:
    replicas: 1
    image: swr.cn-east-3.myhuaweicloud.com/lansefenbao/ops-api:v2.6.1
  frontend:
    replicas: 1
    image: swr.cn-east-3.myhuaweicloud.com/lansefenbao/ops-web:v2.6.1


##################################################
############ Service 相关配置 #####################
##################################################
service:
  # 设置service的type，ClusterIP or NodePort
  type: ClusterIP


##################################################
############ Ingress 相关配置 #####################
##################################################
ingress:
  # 如果设置为`true`，则启用Ingress将平台暴露到外部
  # @type: boolean
  enabled: true

  # 设置ingressClassName
  ingressClassName: ""

  # 指定外部访问域名
  domainName: ""

  # TLS相关配置
  # ```yaml
  # tls:
  #   hosts: "example.com"
  #   secretName: testsecret-tls
  # ```
  # @type: map
  tls: {}
